include: package:flutter_lints/flutter.yaml

formatter:
  preserve_trailing_commas: true

linter:
  rules:
    - unused_import: true

    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - require_trailing_commas
    - always_specify_types
analyzer:
  errors:
    use_build_context_synchronously: ignore
    strict_top_level_inference: ignore
    unnecessary_overrides: ignore
